use_frameworks!

target 'ALEither_Example' do
  pod 'ALEither', :path => '../'

  target 'ALEither_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
